name: PR Title Check

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          # regex: '([a-z])+\/([a-z])+' # Regex the title should match.
          allowed_prefixes: "[FEAT],[INFRA]" # title should start with the given prefix
          prefix_case_sensitive: true # title prefix are case insensitive
          min_length: 5 # Min length of the title